// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_BackgroundScreen = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BackgroundController_WakeUp(e);
    }
}

// build funtions

void ui_BackgroundScreen_screen_init(void)
{
    ui_BackgroundScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BackgroundScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container5 = lv_obj_create(ui_BackgroundScreen);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_height(ui_Container5, lv_pct(100));
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton2 = lv_imgbtn_create(ui_Container5);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_33876936, NULL);
    lv_obj_set_width(ui_ImgButton2, lv_pct(100));
    lv_obj_set_height(ui_ImgButton2, lv_pct(100));
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Label5 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, lv_pct(-30));
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "3:42");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);

}

void ui_BackgroundScreen_screen_destroy(void)
{
    if(ui_BackgroundScreen) lv_obj_del(ui_BackgroundScreen);

    // NULL screen variables
    ui_BackgroundScreen = NULL;
    ui_Container5 = NULL;
    ui_ImgButton2 = NULL;
    ui_Label5 = NULL;

}
