// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_ChangeScreenScreen = NULL;
lv_obj_t * ui_AppSelectionRoller = NULL;
lv_obj_t * ui_ConfirmSelectionRoller = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions

// build funtions

void ui_ChangeScreenScreen_screen_init(void)
{
    ui_ChangeScreenScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ChangeScreenScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AppSelectionRoller = lv_roller_create(ui_ChangeScreenScreen);
    lv_roller_set_options(ui_AppSelectionRoller, "Home\nPlaylists\nCharging\nTodo\nSettings\n", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_AppSelectionRoller, 100);
    lv_obj_set_width(ui_AppSelectionRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_AppSelectionRoller, -1);
    lv_obj_set_y(ui_AppSelectionRoller, -11);
    lv_obj_set_align(ui_AppSelectionRoller, LV_ALIGN_CENTER);

    ui_ConfirmSelectionRoller = lv_btn_create(ui_ChangeScreenScreen);
    lv_obj_set_width(ui_ConfirmSelectionRoller, 100);
    lv_obj_set_height(ui_ConfirmSelectionRoller, 50);
    lv_obj_set_x(ui_ConfirmSelectionRoller, 1);
    lv_obj_set_y(ui_ConfirmSelectionRoller, 117);
    lv_obj_set_align(ui_ConfirmSelectionRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfirmSelectionRoller, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfirmSelectionRoller, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_ConfirmSelectionRoller);
    lv_img_set_src(ui_Image1, &ui_img_check_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 50);

}

void ui_ChangeScreenScreen_screen_destroy(void)
{
    if(ui_ChangeScreenScreen) lv_obj_del(ui_ChangeScreenScreen);

    // NULL screen variables
    ui_ChangeScreenScreen = NULL;
    ui_AppSelectionRoller = NULL;
    ui_ConfirmSelectionRoller = NULL;
    ui_Image1 = NULL;

}
