// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#ifndef UI_CHANGESCREENSCREEN_H
#define UI_CHANGESCREENSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ChangeScreenScreen
extern void ui_ChangeScreenScreen_screen_init(void);
extern void ui_ChangeScreenScreen_screen_destroy(void);
extern lv_obj_t * ui_ChangeScreenScreen;
extern lv_obj_t * ui_AppSelectionRoller;
extern lv_obj_t * ui_ConfirmSelectionRoller;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

