// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container_controlls;
extern lv_obj_t * ui_Button_Previous;
extern lv_obj_t * ui_Button_PlayPause;
extern lv_obj_t * ui_Button_Next;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label_Time;
extern lv_obj_t * ui_Panel_devider;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

