// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Container_controlls = NULL;
lv_obj_t * ui_Button_Previous = NULL;
lv_obj_t * ui_Button_PlayPause = NULL;
lv_obj_t * ui_Button_Next = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Label_Time = NULL;
lv_obj_t * ui_Panel_devider = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 372);
    lv_obj_set_height(ui_Container1, 364);
    lv_obj_set_x(ui_Container1, 2);
    lv_obj_set_y(ui_Container1, 0);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container1, &ui_img_33876936, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_controlls = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_Container_controlls);
    lv_obj_set_width(ui_Container_controlls, 212);
    lv_obj_set_height(ui_Container_controlls, 66);
    lv_obj_set_x(ui_Container_controlls, 0);
    lv_obj_set_y(ui_Container_controlls, -33);
    lv_obj_set_align(ui_Container_controlls, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container_controlls, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container_controlls, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_controlls, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container_controlls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container_controlls, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Previous = lv_btn_create(ui_Container_controlls);
    lv_obj_set_width(ui_Button_Previous, 54);
    lv_obj_set_height(ui_Button_Previous, 54);
    lv_obj_set_x(ui_Button_Previous, 25);
    lv_obj_set_y(ui_Button_Previous, 21);
    lv_obj_set_align(ui_Button_Previous, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_Previous, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Previous, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button_Previous, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Previous, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Previous, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Previous, &ui_img_1799517327, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Previous, &ui_img_1799517327, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_Button_Previous, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Button_PlayPause = lv_btn_create(ui_Container_controlls);
    lv_obj_set_width(ui_Button_PlayPause, 54);
    lv_obj_set_height(ui_Button_PlayPause, 54);
    lv_obj_set_x(ui_Button_PlayPause, 25);
    lv_obj_set_y(ui_Button_PlayPause, 21);
    lv_obj_set_align(ui_Button_PlayPause, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button_PlayPause, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Button_PlayPause, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_PlayPause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button_PlayPause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_PlayPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_PlayPause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_PlayPause, &ui_img_1898897582, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_PlayPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button_PlayPause, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_Button_PlayPause, &ui_img_1779231396, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Button_PlayPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button_PlayPause, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(ui_Button_PlayPause, &ui_img_1898897582, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_Button_PlayPause, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Button_Next = lv_btn_create(ui_Container_controlls);
    lv_obj_set_width(ui_Button_Next, 54);
    lv_obj_set_height(ui_Button_Next, 54);
    lv_obj_set_x(ui_Button_Next, 25);
    lv_obj_set_y(ui_Button_Next, 21);
    lv_obj_set_align(ui_Button_Next, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_Next, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button_Next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_Next, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Next, &ui_img_1997223691, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_Next, &ui_img_1997223691, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_Button_Next, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Bar1 = lv_bar_create(ui_HomeScreen);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 235);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 6);
    lv_obj_set_y(ui_Bar1, 86);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Bar1, lv_color_hex(0x8181FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x2BDDCE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label_Time = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label_Time, 107);
    lv_obj_set_height(ui_Label_Time, 16);
    lv_obj_set_x(ui_Label_Time, 104);
    lv_obj_set_y(ui_Label_Time, 84);
    lv_obj_set_align(ui_Label_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Time, "10:10");
    lv_obj_set_style_text_align(ui_Label_Time, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_devider = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_Panel_devider, 235);
    lv_obj_set_height(ui_Panel_devider, 3);
    lv_obj_set_x(ui_Panel_devider, 0);
    lv_obj_set_y(ui_Panel_devider, 60);
    lv_obj_set_align(ui_Panel_devider, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel_devider, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel_devider, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_devider, lv_color_hex(0x202420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_devider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_devider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_Image5, &ui_img_1224885811);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image5, -134);
    lv_obj_set_y(ui_Image5, 60);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_Image6, &ui_img_267335790);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image6, 137);
    lv_obj_set_y(ui_Image6, 60);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -131);
    lv_obj_set_y(ui_Label2, 88);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "1:34");

    ui_Label4 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -4);
    lv_obj_set_y(ui_Label4, -146);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "song title");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 6);
    lv_obj_set_y(ui_Label5, -126);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "artest");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_Container1 = NULL;
    ui_Container_controlls = NULL;
    ui_Button_Previous = NULL;
    ui_Button_PlayPause = NULL;
    ui_Button_Next = NULL;
    ui_Bar1 = NULL;
    ui_Label_Time = NULL;
    ui_Panel_devider = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Label2 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;

}
