// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#ifndef UI_PLAYLISTSSCREEN_H
#define UI_PLAYLISTSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PlaylistsScreen
extern void ui_PlaylistsScreen_screen_init(void);
extern void ui_PlaylistsScreen_screen_destroy(void);
extern lv_obj_t * ui_PlaylistsScreen;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

