// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Bar4 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Bar5 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Bar6 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Label15 = NULL;
// event funtions

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 372);
    lv_obj_set_height(ui_Container9, 364);
    lv_obj_set_x(ui_Container9, 2);
    lv_obj_set_y(ui_Container9, 0);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container9, &ui_img_33876936, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_Screen7);
    lv_bar_set_value(ui_Bar4, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 24);
    lv_obj_set_height(ui_Bar4, 172);
    lv_obj_set_x(ui_Bar4, 71);
    lv_obj_set_y(ui_Bar4, -14);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);

    ui_Image10 = lv_img_create(ui_Screen7);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, 72);
    lv_obj_set_y(ui_Image10, 90);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 90);

    ui_Image3 = lv_img_create(ui_Screen7);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 69);
    lv_obj_set_y(ui_Image3, -121);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 90);

    ui_Bar5 = lv_bar_create(ui_Screen7);
    lv_bar_set_value(ui_Bar5, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar5, 59);
    lv_obj_set_height(ui_Bar5, 36);
    lv_obj_set_x(ui_Bar5, -97);
    lv_obj_set_y(ui_Bar5, -39);
    lv_obj_set_align(ui_Bar5, LV_ALIGN_CENTER);

    ui_Image12 = lv_img_create(ui_Screen7);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, 5);
    lv_obj_set_y(ui_Image12, -84);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image12, 250);

    ui_Label13 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -2);
    lv_obj_set_y(ui_Label13, 148);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "3: 42");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_Screen7);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, -106);
    lv_obj_set_y(ui_Image13, -104);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image13, 160);

    ui_Image14 = lv_img_create(ui_Screen7);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, -60);
    lv_obj_set_y(ui_Image14, -104);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image14, 160);

    ui_Label14 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -7);
    lv_obj_set_y(ui_Label14, -154);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Tue mar 17");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar6 = lv_bar_create(ui_Screen7);
    lv_bar_set_value(ui_Bar6, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar6, 24);
    lv_obj_set_height(ui_Bar6, 178);
    lv_obj_set_x(ui_Bar6, 124);
    lv_obj_set_y(ui_Bar6, -17);
    lv_obj_set_align(ui_Bar6, LV_ALIGN_CENTER);

    ui_Image15 = lv_img_create(ui_Screen7);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, -103);
    lv_obj_set_y(ui_Image15, 42);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "dminjwe");

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Container9 = NULL;
    ui_Bar4 = NULL;
    ui_Image10 = NULL;
    ui_Image3 = NULL;
    ui_Bar5 = NULL;
    ui_Image12 = NULL;
    ui_Label13 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;
    ui_Label14 = NULL;
    ui_Bar6 = NULL;
    ui_Image15 = NULL;
    ui_Label15 = NULL;

}
