// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_Screen8 = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Arc3 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions

// build funtions

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container11 = lv_obj_create(ui_Screen8);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 372);
    lv_obj_set_height(ui_Container11, 364);
    lv_obj_set_x(ui_Container11, 2);
    lv_obj_set_y(ui_Container11, 0);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container11, &ui_img_33876936, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_Screen8);
    lv_obj_set_width(ui_Arc3, lv_pct(50));
    lv_obj_set_height(ui_Arc3, lv_pct(50));
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc3, 20);
    lv_arc_set_rotation(ui_Arc3, -90);

    lv_obj_set_style_bg_img_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Arc3, lv_color_hex(0xA3A3FE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 25);
    lv_obj_set_y(ui_Label9, 5);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Charging");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen8_screen_destroy(void)
{
    if(ui_Screen8) lv_obj_del(ui_Screen8);

    // NULL screen variables
    ui_Screen8 = NULL;
    ui_Container11 = NULL;
    ui_Arc3 = NULL;
    ui_Label9 = NULL;

}
