// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_Root = NULL;
lv_obj_t * ui_ScreenTitle = NULL;
lv_obj_t * ui_ConnectivitySettings = NULL;
lv_obj_t * ui_WifiSettings = NULL;
lv_obj_t * ui_WifiSettingLabel2 = NULL;
lv_obj_t * ui_WiFiLabel2 = NULL;
lv_obj_t * ui_WiFiIcon2 = NULL;
lv_obj_t * ui_ConfigureWifiButton = NULL;
lv_obj_t * ui_WifiButtonText = NULL;
lv_obj_t * ui_BluetoothSettings = NULL;
lv_obj_t * ui_BluetoothSettingLabel = NULL;
lv_obj_t * ui_BluetoothLabel = NULL;
lv_obj_t * ui_BluetoothIcon = NULL;
lv_obj_t * ui_ConfigureBluetoothButton = NULL;
lv_obj_t * ui_WifiButtonText2 = NULL;
// event funtions

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Root = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Root);
    lv_obj_set_width(ui_Root, lv_pct(100));
    lv_obj_set_height(ui_Root, lv_pct(100));
    lv_obj_set_align(ui_Root, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Root, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenTitle = lv_label_create(ui_Root);
    lv_obj_set_width(ui_ScreenTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenTitle, 0);
    lv_obj_set_y(ui_ScreenTitle, -155);
    lv_obj_set_align(ui_ScreenTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenTitle, "Settings");

    ui_ConnectivitySettings = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_ConnectivitySettings);
    lv_obj_set_height(ui_ConnectivitySettings, 150);
    lv_obj_set_width(ui_ConnectivitySettings, lv_pct(100));
    lv_obj_set_x(ui_ConnectivitySettings, 0);
    lv_obj_set_y(ui_ConnectivitySettings, -70);
    lv_obj_set_align(ui_ConnectivitySettings, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConnectivitySettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiSettings = lv_obj_create(ui_ConnectivitySettings);
    lv_obj_remove_style_all(ui_WifiSettings);
    lv_obj_set_height(ui_WifiSettings, 50);
    lv_obj_set_width(ui_WifiSettings, lv_pct(90));
    lv_obj_set_x(ui_WifiSettings, 0);
    lv_obj_set_y(ui_WifiSettings, lv_pct(-25));
    lv_obj_set_align(ui_WifiSettings, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiSettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiSettingLabel2 = lv_obj_create(ui_WifiSettings);
    lv_obj_remove_style_all(ui_WifiSettingLabel2);
    lv_obj_set_height(ui_WifiSettingLabel2, 50);
    lv_obj_set_width(ui_WifiSettingLabel2, lv_pct(50));
    lv_obj_set_y(ui_WifiSettingLabel2, 0);
    lv_obj_set_x(ui_WifiSettingLabel2, lv_pct(-25));
    lv_obj_set_align(ui_WifiSettingLabel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiSettingLabel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiLabel2 = lv_label_create(ui_WifiSettingLabel2);
    lv_obj_set_width(ui_WiFiLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_WiFiLabel2, 0);
    lv_obj_set_x(ui_WiFiLabel2, lv_pct(25));
    lv_obj_set_align(ui_WiFiLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiLabel2, "\nWiFi\n");
    lv_obj_set_style_text_font(ui_WiFiLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiIcon2 = lv_img_create(ui_WifiSettingLabel2);
    lv_img_set_src(ui_WiFiIcon2, &ui_img_wifi_png);
    lv_obj_set_width(ui_WiFiIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_WiFiIcon2, 0);
    lv_obj_set_x(ui_WiFiIcon2, lv_pct(-10));
    lv_obj_set_align(ui_WiFiIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiIcon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WiFiIcon2, 60);

    ui_ConfigureWifiButton = lv_btn_create(ui_WifiSettings);
    lv_obj_set_height(ui_ConfigureWifiButton, 50);
    lv_obj_set_width(ui_ConfigureWifiButton, lv_pct(30));
    lv_obj_set_y(ui_ConfigureWifiButton, 0);
    lv_obj_set_x(ui_ConfigureWifiButton, lv_pct(20));
    lv_obj_set_align(ui_ConfigureWifiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigureWifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigureWifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButtonText = lv_label_create(ui_ConfigureWifiButton);
    lv_obj_set_width(ui_WifiButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiButtonText, "Configure");

    ui_BluetoothSettings = lv_obj_create(ui_ConnectivitySettings);
    lv_obj_remove_style_all(ui_BluetoothSettings);
    lv_obj_set_height(ui_BluetoothSettings, 50);
    lv_obj_set_width(ui_BluetoothSettings, lv_pct(90));
    lv_obj_set_x(ui_BluetoothSettings, 0);
    lv_obj_set_y(ui_BluetoothSettings, lv_pct(25));
    lv_obj_set_align(ui_BluetoothSettings, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BluetoothSettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BluetoothSettingLabel = lv_obj_create(ui_BluetoothSettings);
    lv_obj_remove_style_all(ui_BluetoothSettingLabel);
    lv_obj_set_height(ui_BluetoothSettingLabel, 50);
    lv_obj_set_width(ui_BluetoothSettingLabel, lv_pct(50));
    lv_obj_set_y(ui_BluetoothSettingLabel, 0);
    lv_obj_set_x(ui_BluetoothSettingLabel, lv_pct(-25));
    lv_obj_set_align(ui_BluetoothSettingLabel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BluetoothSettingLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BluetoothLabel = lv_label_create(ui_BluetoothSettingLabel);
    lv_obj_set_width(ui_BluetoothLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BluetoothLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_BluetoothLabel, 0);
    lv_obj_set_x(ui_BluetoothLabel, lv_pct(18));
    lv_obj_set_align(ui_BluetoothLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BluetoothLabel, "Bluetooth");
    lv_obj_set_style_text_font(ui_BluetoothLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BluetoothIcon = lv_img_create(ui_BluetoothSettingLabel);
    lv_img_set_src(ui_BluetoothIcon, &ui_img_821000619);
    lv_obj_set_width(ui_BluetoothIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BluetoothIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_BluetoothIcon, 0);
    lv_obj_set_x(ui_BluetoothIcon, lv_pct(-35));
    lv_obj_set_align(ui_BluetoothIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BluetoothIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BluetoothIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BluetoothIcon, 60);

    ui_ConfigureBluetoothButton = lv_btn_create(ui_BluetoothSettings);
    lv_obj_set_height(ui_ConfigureBluetoothButton, 50);
    lv_obj_set_width(ui_ConfigureBluetoothButton, lv_pct(30));
    lv_obj_set_y(ui_ConfigureBluetoothButton, 0);
    lv_obj_set_x(ui_ConfigureBluetoothButton, lv_pct(20));
    lv_obj_set_align(ui_ConfigureBluetoothButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigureBluetoothButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigureBluetoothButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButtonText2 = lv_label_create(ui_ConfigureBluetoothButton);
    lv_obj_set_width(ui_WifiButtonText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiButtonText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiButtonText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiButtonText2, "Configure");

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_Root = NULL;
    ui_ScreenTitle = NULL;
    ui_ConnectivitySettings = NULL;
    ui_WifiSettings = NULL;
    ui_WifiSettingLabel2 = NULL;
    ui_WiFiLabel2 = NULL;
    ui_WiFiIcon2 = NULL;
    ui_ConfigureWifiButton = NULL;
    ui_WifiButtonText = NULL;
    ui_BluetoothSettings = NULL;
    ui_BluetoothSettingLabel = NULL;
    ui_BluetoothLabel = NULL;
    ui_BluetoothIcon = NULL;
    ui_ConfigureBluetoothButton = NULL;
    ui_WifiButtonText2 = NULL;

}
