// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#ifndef UI_SCREEN7_H
#define UI_SCREEN7_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen7
extern void ui_Screen7_screen_init(void);
extern void ui_Screen7_screen_destroy(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Bar5;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Bar6;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

