// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Player

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Panel_volume;
extern lv_obj_t * ui_Arc_Volume;
extern lv_obj_t * ui_Panel_brightness;
extern lv_obj_t * ui_Arc_Brightness;
extern lv_obj_t * ui_Container_controlls;
extern lv_obj_t * ui_Button_Previous;
extern lv_obj_t * ui_Button_PlayPause;
extern lv_obj_t * ui_Button_Next;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Roller_list;
extern lv_obj_t * ui_Label_Time;
extern lv_obj_t * ui_Panel_devider;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Button_Mode;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

