// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_makebed;
extern lv_obj_t * ui_Checkbox3;
extern lv_obj_t * ui_Checkbox4;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Checkbox5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

