// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Colorwheel5 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Slider3 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container8 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 372);
    lv_obj_set_height(ui_Container8, 364);
    lv_obj_set_x(ui_Container8, 2);
    lv_obj_set_y(ui_Container8, 0);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container8, &ui_img_33876936, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel5 = lv_colorwheel_create(ui_Screen6, true);
    lv_obj_set_width(ui_Colorwheel5, 150);
    lv_obj_set_height(ui_Colorwheel5, 150);
    lv_obj_set_x(ui_Colorwheel5, -49);
    lv_obj_set_y(ui_Colorwheel5, -52);
    lv_obj_set_align(ui_Colorwheel5, LV_ALIGN_CENTER);

    ui_Image4 = lv_img_create(ui_Screen6);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, lv_pct(25));
    lv_obj_set_y(ui_Image4, lv_pct(0));
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 300);

    ui_Slider3 = lv_slider_create(ui_Screen6);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 231);
    lv_obj_set_height(ui_Slider3, 10);
    lv_obj_set_x(ui_Slider3, -1);
    lv_obj_set_y(ui_Slider3, 95);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -121);
    lv_obj_set_y(ui_Label8, 55);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Add");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Container8 = NULL;
    ui_Colorwheel5 = NULL;
    ui_Image4 = NULL;
    ui_Slider3 = NULL;
    ui_Label8 = NULL;

}
