// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_Root;
extern lv_obj_t * ui_ScreenTitle;
extern lv_obj_t * ui_ConnectivitySettings;
extern lv_obj_t * ui_WifiSettings;
extern lv_obj_t * ui_WifiSettingLabel2;
extern lv_obj_t * ui_WiFiLabel2;
extern lv_obj_t * ui_WiFiIcon2;
extern lv_obj_t * ui_ConfigureWifiButton;
extern lv_obj_t * ui_WifiButtonText;
extern lv_obj_t * ui_BluetoothSettings;
extern lv_obj_t * ui_BluetoothSettingLabel;
extern lv_obj_t * ui_BluetoothLabel;
extern lv_obj_t * ui_BluetoothIcon;
extern lv_obj_t * ui_ConfigureBluetoothButton;
extern lv_obj_t * ui_WifiButtonText2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

