// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Colorwheel4 = NULL;
// event funtions

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 372);
    lv_obj_set_height(ui_Container7, 364);
    lv_obj_set_x(ui_Container7, 2);
    lv_obj_set_y(ui_Container7, 0);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container7, &ui_img_33876936, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel4 = lv_colorwheel_create(ui_Screen5, true);
    lv_obj_set_width(ui_Colorwheel4, lv_pct(50));
    lv_obj_set_height(ui_Colorwheel4, lv_pct(50));
    lv_obj_set_x(ui_Colorwheel4, -1);
    lv_obj_set_y(ui_Colorwheel4, -5);
    lv_obj_set_align(ui_Colorwheel4, LV_ALIGN_CENTER);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Container7 = NULL;
    ui_Colorwheel4 = NULL;

}
