// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#ifndef UI_TODOSCREEN_H
#define UI_TODOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ToDoScreen
extern void ui_ToDoScreen_screen_init(void);
extern void ui_ToDoScreen_screen_destroy(void);
extern lv_obj_t * ui_ToDoScreen;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_makebed;
extern lv_obj_t * ui_Checkbox3;
extern lv_obj_t * ui_Checkbox4;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Checkbox5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

