// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_WifiConnectScreen = NULL;
lv_obj_t * ui_WifiConnectScreenContainer = NULL;
lv_obj_t * ui_WifiSSIDList = NULL;
lv_obj_t * ui_SelectButton = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_CancelButton = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions
void ui_event_WifiConnectScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        WifiConnectController_SSIDScreenLoaded(e);
    }
}

void ui_event_SelectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        WifiConnectController_SSIDSelectClicked(e);
    }
}

void ui_event_CancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        WifiConnectController_SSIDCancelClicked(e);
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_SettingsScreen_screen_init);
    }
}

// build funtions

void ui_WifiConnectScreen_screen_init(void)
{
    ui_WifiConnectScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiConnectScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiConnectScreenContainer = lv_obj_create(ui_WifiConnectScreen);
    lv_obj_remove_style_all(ui_WifiConnectScreenContainer);
    lv_obj_set_width(ui_WifiConnectScreenContainer, lv_pct(100));
    lv_obj_set_height(ui_WifiConnectScreenContainer, lv_pct(100));
    lv_obj_set_align(ui_WifiConnectScreenContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiConnectScreenContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiSSIDList = lv_roller_create(ui_WifiConnectScreenContainer);
    lv_obj_set_height(ui_WifiSSIDList, 150);
    lv_obj_set_width(ui_WifiSSIDList, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_WifiSSIDList, LV_ALIGN_CENTER);

    ui_SelectButton = lv_button_create(ui_WifiConnectScreenContainer);
    lv_obj_set_width(ui_SelectButton, 150);
    lv_obj_set_height(ui_SelectButton, 75);
    lv_obj_set_x(ui_SelectButton, 0);
    lv_obj_set_y(ui_SelectButton, 120);
    lv_obj_set_align(ui_SelectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SelectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SelectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_SelectButton);
    lv_obj_set_width(ui_Label1, lv_pct(50));
    lv_obj_set_height(ui_Label1, lv_pct(50));
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_x(ui_Label1, lv_pct(35));
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Select");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_SelectButton);
    lv_image_set_src(ui_Image1, &ui_img_check_png);
    lv_obj_set_width(ui_Image1, lv_pct(50));
    lv_obj_set_height(ui_Image1, lv_pct(100));
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_x(ui_Image1, lv_pct(-25));
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image1, 64);

    ui_CancelButton = lv_button_create(ui_WifiConnectScreenContainer);
    lv_obj_set_width(ui_CancelButton, 150);
    lv_obj_set_height(ui_CancelButton, 75);
    lv_obj_set_x(ui_CancelButton, 0);
    lv_obj_set_y(ui_CancelButton, -120);
    lv_obj_set_align(ui_CancelButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CancelButton, lv_color_hex(0xE20D25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_CancelButton);
    lv_obj_set_width(ui_Label2, lv_pct(55));
    lv_obj_set_height(ui_Label2, lv_pct(50));
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_x(ui_Label2, lv_pct(35));
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Cancel\n");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_CancelButton);
    lv_image_set_src(ui_Image2, &ui_img_x_png);
    lv_obj_set_width(ui_Image2, lv_pct(50));
    lv_obj_set_height(ui_Image2, lv_pct(100));
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_x(ui_Image2, lv_pct(-25));
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 64);

    lv_obj_add_event_cb(ui_SelectButton, ui_event_SelectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CancelButton, ui_event_CancelButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiConnectScreen, ui_event_WifiConnectScreen, LV_EVENT_ALL, NULL);

}

void ui_WifiConnectScreen_screen_destroy(void)
{
    if(ui_WifiConnectScreen) lv_obj_del(ui_WifiConnectScreen);

    // NULL screen variables
    ui_WifiConnectScreen = NULL;
    ui_WifiConnectScreenContainer = NULL;
    ui_WifiSSIDList = NULL;
    ui_SelectButton = NULL;
    ui_Label1 = NULL;
    ui_Image1 = NULL;
    ui_CancelButton = NULL;
    ui_Label2 = NULL;
    ui_Image2 = NULL;

}
