// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Player

#include "../ui.h"

lv_obj_t * ui_BackgroundScreen = NULL;
lv_obj_t * ui_BackgroundContainer = NULL;
lv_obj_t * ui_BackgroundImage = NULL;
lv_obj_t * ui_Time = NULL;
// event funtions
void ui_event_BackgroundImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BackgroundController_WakeUp(e);
    }
}

// build funtions

void ui_BackgroundScreen_screen_init(void)
{
    ui_BackgroundScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BackgroundScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackgroundContainer = lv_obj_create(ui_BackgroundScreen);
    lv_obj_remove_style_all(ui_BackgroundContainer);
    lv_obj_set_width(ui_BackgroundContainer, lv_pct(100));
    lv_obj_set_height(ui_BackgroundContainer, lv_pct(100));
    lv_obj_set_align(ui_BackgroundContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BackgroundContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackgroundImage = lv_imagebutton_create(ui_BackgroundContainer);
    lv_imagebutton_set_src(ui_BackgroundImage, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_33876936, NULL);
    lv_obj_set_width(ui_BackgroundImage, lv_pct(100));
    lv_obj_set_height(ui_BackgroundImage, lv_pct(100));
    lv_obj_set_align(ui_BackgroundImage, LV_ALIGN_CENTER);

    ui_Time = lv_label_create(ui_BackgroundContainer);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 0);
    lv_obj_set_y(ui_Time, lv_pct(-30));
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "3:42");
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackgroundImage, ui_event_BackgroundImage, LV_EVENT_ALL, NULL);

}

void ui_BackgroundScreen_screen_destroy(void)
{
    if(ui_BackgroundScreen) lv_obj_del(ui_BackgroundScreen);

    // NULL screen variables
    ui_BackgroundScreen = NULL;
    ui_BackgroundContainer = NULL;
    ui_BackgroundImage = NULL;
    ui_Time = NULL;

}
