// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Player

#ifndef UI_WIFICONNECTSCREEN_H
#define UI_WIFICONNECTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiConnectScreen
extern void ui_WifiConnectScreen_screen_init(void);
extern void ui_WifiConnectScreen_screen_destroy(void);
extern void ui_event_WifiConnectScreen(lv_event_t * e);
extern lv_obj_t * ui_WifiConnectScreen;
extern lv_obj_t * ui_WifiConnectScreenContainer;
extern lv_obj_t * ui_WifiSSIDList;
extern void ui_event_SelectButton(lv_event_t * e);
extern lv_obj_t * ui_SelectButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern void ui_event_CancelButton(lv_event_t * e);
extern lv_obj_t * ui_CancelButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

