// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

// COMPONENT makebed

lv_obj_t * ui_makebed_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_makebed;
    cui_makebed = lv_checkbox_create(comp_parent);
    lv_obj_set_width(cui_makebed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_makebed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_makebed, lv_pct(-16));
    lv_obj_set_y(cui_makebed, lv_pct(-22));
    lv_obj_set_align(cui_makebed, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_makebed, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(cui_makebed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_makebed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_makebed, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(cui_makebed, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(cui_makebed, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MAKEBED_NUM);
    children[UI_COMP_MAKEBED_MAKEBED] = cui_makebed;
    lv_obj_add_event_cb(cui_makebed, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_makebed, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_makebed_create_hook(cui_makebed);
    return cui_makebed;
}

