// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Player

#ifndef _PLAYER_UI_H
#define _PLAYER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_33876936);    // assets/Images/pexels-photo-998641.png
LV_IMG_DECLARE(ui_img_1799517327);    // assets/Images/icon-previous.png
LV_IMG_DECLARE(ui_img_1898897582);    // assets/Images/icon-play.png
LV_IMG_DECLARE(ui_img_1779231396);    // assets/Images/icon-pause.png
LV_IMG_DECLARE(ui_img_1997223691);    // assets/Images/icon-next.png
LV_IMG_DECLARE(ui_img_1224885811);    // assets/Images/icon-brightness.png
LV_IMG_DECLARE(ui_img_267335790);    // assets/Images/icon-volume.png
LV_IMG_DECLARE(ui_img_295812069);    // assets/Images/icon-music.png
LV_IMG_DECLARE(ui_img_1947372027);    // assets/Images/icon-radio.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
