// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Player

#include "ui.h"

void BackgroundController_WakeUp(lv_event_t * e)
{
	// Your code here
}
