// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Player

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void BackgroundController_WakeUp(lv_event_t * e);
void WifiConnectController_SSIDScreenLoaded(lv_event_t * e);
void WifiConnectController_SSIDSelectClicked(lv_event_t * e);
void WifiConnectController_SSIDCancelClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
