// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Player

#ifndef _PLAYER_UI_H
#define _PLAYER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MusicScreen.h"
#include "screens/ui_SettingsScreen.h"
#include "screens/ui_BackgroundScreen.h"
#include "screens/ui_WifiConnectScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_33876936);    // assets/Images/pexels-photo-998641.png
LV_IMG_DECLARE(ui_img_1799517327);    // assets/Images/icon-previous.png
LV_IMG_DECLARE(ui_img_1898897582);    // assets/Images/icon-play.png
LV_IMG_DECLARE(ui_img_1779231396);    // assets/Images/icon-pause.png
LV_IMG_DECLARE(ui_img_1997223691);    // assets/Images/icon-next.png
LV_IMG_DECLARE(ui_img_1224885811);    // assets/Images/icon-brightness.png
LV_IMG_DECLARE(ui_img_267335790);    // assets/Images/icon-volume.png
LV_IMG_DECLARE(ui_img_295812069);    // assets/Images/icon-music.png
LV_IMG_DECLARE(ui_img_1947372027);    // assets/Images/icon-radio.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_821000619);    // assets/bluetooth-connected.png
LV_IMG_DECLARE(ui_img_check_png);    // assets/check.png
LV_IMG_DECLARE(ui_img_x_png);    // assets/x.png
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_bg3_png);    // assets/bg3.png
LV_IMG_DECLARE(ui_img_bg4_png);    // assets/bg4.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
